using System;
using System.Collections.Generic;
using System.Text;

namespace CoinMixer
{
    /*
     * Logger class defines the various log files generated by log4net library
     */
    public static class Logger
    {
        public const string EventQueue = "EventQueue";
        public const string RequestResponse = "RequestResponse";
        public const string Mixer = "Mixer";
    }
}
